version: "3.9"

services:
  api:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - MONGO_URI=mongodb://mongo:27017
      - MONGO_DB=sreechat
      - REDIS_ADDR=redis:6379
      - JWT_SECRET=9f8c2e7a4b1d6c3e5f9a0b2c7d8e1f4a6b3c9d0e7f2a5b8c1d6e3f9a4b7c2d1
      - CORS_ORIGIN=http://localhost:5173
    depends_on:
      - mongo
      - redis
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "3000:80"
  #   depends_on:
  #     - api
  #   restart: unless-stopped

volumes:
  mongo_data:
