version: "3.9"

services:
  api:
    build: ./backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - mongo
      - redis
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data

  mongo:
    image: mongo:7
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped


volumes:
  mongo_data:
  redis_data:
